@startuml
scale 1.5

interface Healable {
    {abstract} void heal()
}

interface Attackable {
    {abstract} void attack()
}

class Cleric extends Character {
    + void attack()
    - void die()
}

abstract class Character implements Attackable {
    + int hp
    - int mp
    {abstract} void attack(Slime slime)
}

class Hero extends Character {
    void attack(Slime slime)
    void run()
}

class SuperHero extends Hero implements Healable {
    Sword sword

    void attack(Slime slime)
}

@enduml